quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.database.generation=validate
kafka.bootstrap.servers=localhost:9092

%docker.quarkus.devservices.enabled=false
%docker.kafka.bootstrap.servers=kafka:29092
%docker.quarkus.datasource.jdbc.url=jdbc:mysql://mysql:3306/orders
%docker.quarkus.datasource.username=florinda
%docker.quarkus.datasource.password=florinda
%docker.quarkus.datasource.reactive.url=mysql://mysql:3306/orders
